version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: telemetry-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: telemetry-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  telemetry-server:
    build: .
    container_name: telemetry-server
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=dev
      - MONGO_URI=mongodb://admin:password@mongodb:27017
      - REDIS_URI=redis://redis:6379
      - PORT=8080
    depends_on:
      - mongodb
      - redis

volumes:
  mongo-data:
  redis-data: